name: DotNet Build and Manual Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release'
        required: true
        default: 'beta'
        type: choice
        options:
          - beta
          - stable
      version:
        description: 'Version to release'
        required: true
        type: string

jobs:
  build:
    name: Build Release
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 10

      - name: Build
        shell: pwsh
        run: |
          $msbuildPath = Split-Path (& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\Current\Bin\amd64\MSBuild.exe | Select-Object -First 1) -Parent
          $env:PATH = $msbuildPath + ';' + $env:PATH
          nuget locals all -clear
          msbuild -v:m -restore -t:Build -p:Configuration=Release MissionPlanner.sln

      - name: Cleanup
        shell: pwsh
        run: |
          cd bin\Release\net461
          gci plugins | ForEach-Object {                 if (Test-Path $_.Name -PathType Leaf)                {                    Write-Host "Remove" $_.FullName   ;                 Remove-Item $_.FullName                            } else {                    Write-Host $_.Name                }            }

          copy version.txt ..\..\..\
          7z a -tzip ..\..\..\MissionPlannerBeta.zip *
          cd ..
          .\md5sum.exe net461 > ..\..\checksums.txt
          
      - uses: actions/upload-artifact@v4
        with:
          name: MissionPlannerBeta
          path: bin\Release\net461
          
  manual-release:
    name: Manual Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: MissionPlannerBeta
      
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ inputs.release_type }}-${{ inputs.version }}"
          prerelease: "${{ inputs.release_type == 'beta' }}"
          title: "${{ inputs.release_type == 'beta' && 'Beta' || 'Stable' }} Release ${{ inputs.version }}"
          files: |
            MissionPlannerBeta.zip
            checksums.txt
            version.txt
            ChangeLog.txt

  buildDebug:
    name: Build Debug
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 10

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            **/obj/**
          key: ${{ runner.os }}-buildDebug

      - name: Build
        shell: pwsh
        run: |
          $msbuildPath = Split-Path (& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\Current\Bin\amd64\MSBuild.exe | Select-Object -First 1) -Parent
          $env:PATH = $msbuildPath + ';' + $env:PATH
          nuget locals all -clear
          msbuild -v:m -restore -t:Build -p:Configuration=Debug MissionPlanner.sln

      - name: Cleanup
        shell: pwsh
        run: |
          cd bin\Debug\net461
          gci plugins | ForEach-Object {                 if (Test-Path $_.Name -PathType Leaf)                {                    Write-Host "Remove" $_.FullName   ;                 Remove-Item $_.FullName                            } else {                    Write-Host $_.Name                }            }
